// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiLdd91VMzjNhbAHPFA7_6CecmQt4DR7U',
    appId: '1:242040908883:web:b5e4d3a3b39ff684772aa6',
    messagingSenderId: '242040908883',
    projectId: 'commodities-exchange-app',
    authDomain: 'commodities-exchange-app.firebaseapp.com',
    databaseURL: 'https://commodities-exchange-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'commodities-exchange-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeQH3GmUGjKfvQzgr0TfhX9HxvxNj6olM',
    appId: '1:242040908883:android:c8ddecd7e77ac2fe772aa6',
    messagingSenderId: '242040908883',
    projectId: 'commodities-exchange-app',
    databaseURL: 'https://commodities-exchange-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'commodities-exchange-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHqduhoRq0_1J-SbOXGK1sg--HvnVZy88',
    appId: '1:242040908883:ios:ab2d5ffaa3587451772aa6',
    messagingSenderId: '242040908883',
    projectId: 'commodities-exchange-app',
    databaseURL: 'https://commodities-exchange-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'commodities-exchange-app.appspot.com',
    iosClientId: '242040908883-56rb9ldsntsqfdkjs7glrl40m17lb6uc.apps.googleusercontent.com',
    iosBundleId: 'com.ingeniousgang.ceapp',
  );
}
