// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiLdd91VMzjNhbAHPFA7_6CecmQt4DR7U',
    appId: '1:242040908883:web:b5e4d3a3b39ff684772aa6',
    messagingSenderId: '242040908883',
    projectId: 'commodities-exchange-app',
    authDomain: 'commodities-exchange-app.firebaseapp.com',
    storageBucket: 'commodities-exchange-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeQH3GmUGjKfvQzgr0TfhX9HxvxNj6olM',
    appId: '1:242040908883:android:1df02f8c5afc152f772aa6',
    messagingSenderId: '242040908883',
    projectId: 'commodities-exchange-app',
    storageBucket: 'commodities-exchange-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHqduhoRq0_1J-SbOXGK1sg--HvnVZy88',
    appId: '1:242040908883:ios:f821ae869486569d772aa6',
    messagingSenderId: '242040908883',
    projectId: 'commodities-exchange-app',
    storageBucket: 'commodities-exchange-app.appspot.com',
    iosClientId: '242040908883-t0d2255iqa5kaedonm2h6ib8acq9g061.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHqduhoRq0_1J-SbOXGK1sg--HvnVZy88',
    appId: '1:242040908883:ios:a5b7fff9225ade35772aa6',
    messagingSenderId: '242040908883',
    projectId: 'commodities-exchange-app',
    storageBucket: 'commodities-exchange-app.appspot.com',
    iosClientId: '242040908883-q0pg2b86ot2bkim6m2bf7ic6cjbdht0o.apps.googleusercontent.com',
    iosBundleId: 'com.ex.app',
  );
}
